baseURL = "https://olaru.dk"
languageCode = "en-us"
title = "iustinian-olaru"
theme="hugo-theme-console"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  # hugo-theme-console specific parameters
  # Cutting off the page title to two chars for mobile (e.g., Personal Profile -> Pe)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, remove/comment the animateStyle parameter
  animateStyle = "animated zoomIn fast"

  [params.og]
  title = "olaru.dk"
  description = "Professional Problem Solver"
  image = "/images/og.png"  # Image shown in previews (1200x630px recommended)

#  [params.twitter]
#  card = "summary_large_image"  # or "summary"
#  site = "@yourhandle"
#  creator = "@yourhandle"

  # Top navigation links
  [[params.navlinks]]
  name = "~/"
  url = ""

  [[params.navlinks]]
  name = "Projects"
  url = "projects/"

  [[params.navlinks]]
  name = "About Me"
  url = "about_me/"

  [[params.navlinks]]
  name = "Philosophy"
  url = "work/"

  # Social links for footer
  [[params.sociallinks]]
  url = "https://www.linkedin.com/in/iustinian-olaru-b73a87387/"
  icon = "fa-linkedin"

  [[params.sociallinks]]
  url = "https://github.com/iustin94"
  icon = "fa-github"

  [[params.sociallinks]]
  url = "https://stackoverflow.com/users/3652652/iustinian-olaru"
  icon = "fa-stack-overflow"