baseURL = "https://olaru.dk"
languageCode = "en-us"
title = "iustinian-olaru"
theme="hugo-theme-console"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  # Google Analytics
  googleAnalyticsID = "G-J4LP1PW7S5"  # Replace with your actual GA4 ID

  # hugo-theme-console specific parameters
  # Cutting off the page title to two chars for mobile (e.g., Personal Profile -> Pe)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, remove/comment the animateStyle parameter
  animateStyle = "animated zoomIn fast"

  # OpenGraph and Twitter Cards
  description = "Software Developer specializing in C#/.NET, full-stack development, and domain-driven design. Based in Denmark."
  title = "Iustinian Olaru"

  [params.og]
    image = "/images/og.png"

  [params.Social]
    twitter = "iustinian_olaru"
    linkedin = "iustinian-olaru-b73a87387"
    github = "iustin94"
    email = "o.iustin@gmail.com"

  [[params.Authors]]
    name = "Iustinian Olaru"
    twitter = "iustinian_olaru"

  # Top navigation links
  [[params.navlinks]]
  name = "home/"
  url = ""

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"

  [[params.navlinks]]
  name = "about_me/"
  url = "about_me/"

  [[params.navlinks]]
  name = "contact/"
  url = "contact/"

  # Social links for footer
  [[params.sociallinks]]
  url = "https://www.linkedin.com/in/iustinian-olaru-b73a87387/"
  icon = "fa-linkedin"

  [[params.sociallinks]]
  url = "https://github.com/iustin94"
  icon = "fa-github"

  [[params.sociallinks]]
  url = "https://stackoverflow.com/users/3652652/iustinian-olaru"
  icon = "fa-stack-overflow"